[package]
name = "procmacro"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0", features = ["full", "visit-mut"] }
quote = "1.0"
proc-macro2 = "1.0.89"
indexmap = "2.12.0"

[lib]
proc-macro = true
path = "./proc.rs"